### ISSUE TITLE
[bug] moon ci doesn't work with a shallow clone

### ISSUE THREAD

**Issue by dudicoco** [moonrepo/moon#1724]
**Describe the bug**

When running `moon ci --base HEAD~1` in CI with a shallow clone we get the following error:
```
[ WARN 2024-11-16 19:28:39.780] moon_app::queries::touched_files  Detected a shallow checkout, unable to run Git commands to determine touched files. 
[ WARN 19:2[8](https://github.com/.../actions/runs/11872654373/job/33086603328#step:4:9):39.780] moon_app::queries::touched_files  A full Git history is required for affected checks, falling back to an empty files list. 
Gathering touched files
  Error: app::ci::no_shallow
    × CI requires a full VCS history to operate correctly. Please avoid shallow
    │ checkouts.
```

I'm opening this as a bug rather than a feature request due to the fact that this error contradicts the `--base` flag.
If we are able to set the base to the last commit we should be able to use it with a shallow clone.
Shallow clones are critical for big monorepos due to the performance improvement they provide.

**Comment by milesj** [comment]
Should be fixed in 1.30.1

**Comment by dudicoco** [comment]
@milesj i've upgraded to the new version and i'm now getting this message:
>	[ WARN 2024-11-28 21:19:10.968] moon_app::queries::touched_files  Detected a shallow checkout, unable to run Git commands to determine touched files.

**Comment by milesj** [comment]
@dudicoco I need more information. Is it still a hard error or just a warning? What command is being ran? On what branch?

**Comment by dudicoco** [comment]
The command is `moon ci --base HEAD~1 --color`, on push to main branch.
It seems like a warning but then I saw errors throughout the run:
```
 Encountered a missing hash for task one:package, which is a dependency of one_prod:push-ci.
  This either means the dependency hasn't ran, has failed, or there's a misconfiguration.
  
  Try disabling the task's cache, or marking it as local.
```
After reverting the command and the shallow clone I still get this errors, so  this version totally broke moon for me.
After reverting to v1.30.0 I'm no longer getting the error.

**Comment by milesj** [comment]
So there's this logic that if `moon ci` is ran on the default branch, it always runs with `HEAD~1` regardless if `--base` is set.

Even though your base is exactly the same, that default branch still runs the shallow checkout logic. Let me update that.

**Comment by milesj** [comment]
This may work better: https://github.com/moonrepo/moon/pull/1741

**Comment by milesj** [comment]
Give 1.30.2 a try.

**Comment by dudicoco** [comment]
@milesj I can confirm this is fixed, thanks!
